### ISSUE TITLE
Puppet 6.0 RHEL8 & Debian 10 support?

### ISSUE THREAD

**Issue by kmarcroft** [ULHPC/puppet-sudo#12]
Hi,

is this module still maintained?
Any chance to see the above being available in the near future?

Thanks

**Comment by Falkor** [comment]
Hi @kmarcroft 

yes, we continue to use it (but are late to update the pending PR I confess). 
We will soon migrate to RHEL8, so this support will naturally comes. Yet we have no longer any Debian 10 machines, so this won't likely come.

**Comment by kmarcroft** [comment]
Hi @Falkor,

kindly ping me once you have RHEL8 support and I might just contribute the Debian 10 support.

Thanks

**Comment by hcartiaux** [comment]
It's done, it simply works on RHEL8 and Rocky 8.
