### ISSUE TITLE
Module doesn't work on Puppet 4 when sudo is not installed

### ISSUE THREAD

**Issue by crispygoth** [ULHPC/puppet-sudo#6]
I just tried to run puppet on a new server which did not have "sudo" installed, and got the following error from this module:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /etc/puppetlabs/code/environments/dev_chrisb/modules/sudo/manifests/common.pp:97:12 on node oxo-drbl.zedcore.com
```

My manifest for sudo is pretty simple (excluding the command defs, obviously):

```
 class { '::sudo':
    ensure              => 'present'
  }
```

Not sure if it's relevant, but the server version is 4.5.2 and the client is currently 3.7.2 (Puppet's first task is to upgrade itself...)

**Comment by Falkor** [comment]
Indeed, the module has not yet been tested against puppet 4. Thanks for reporting this error.

There is a custom fact (in `lib/facter/sudo.rb`) that provides the `::sudoversion` fact.
Could it be that you do not load custom facts prior to your instantiation of the sudo module ?

**Comment by crispygoth** [comment]
I have custom facts in other modules that are being run OK, and if I run the agent with `--debug` it does mention the sudo.rb fact file:

```
Debug: Loading facts from /var/lib/puppet/lib/facter/sudo.rb
```

It looks like this is a breaking change to `versioncmp` made in Puppet 4.3.0, which now enforces that the arguments are strings, and will therefore not accept `undef` as one of the arguments: [PUP-4780](https://tickets.puppetlabs.com/browse/PUP-4780?focusedCommentId=254137&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-254137)

I guess the module either needs to check whether `sudoversion` is defined before trying to `versioncmp` it, or the custom fact should return an empty string instead of undef when sudo is not installed.
